import './globals.css'
import type { Metadata } from 'next'
import { Inter, Autour_One } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
const autourOne = Autour_One({
  weight: '400',
  style: 'normal',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={autourOne.className}>{children}</body>
    </html>
  )
}
